[[inputs]]
name = "player1"
ports = ["player1:out_0", "player1:out_1"]

[[inputs]]
name = "player2"
ports = ["player2:out_0", "player2:out_1"]

[fallback_input]
name = "stream1"
ports = ["stream1:out_0", "stream1:out_1"]

[output]
ports = ["system:playback_1", "system:playback_2"]
